services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.2
    env:
      discovery.type: single-node
    ports:
      - 9200
    volumes:
      - /usr/share/elasticsearch/data
